### ISSUE TITLE
Could you please upload your requirements.txt?

### ISSUE THREAD

**Issue by he159ok** [githwd2016/MATE#2]
Thanks a lot for your instruction in the dev-branch.

May I know the "requirements.txt", which is your environment configure?
At least, it will be much helpful to tell us your PyTorch version.

**Comment by he159ok** [comment]
I have installed PyTorch 1.8.1 with cuda 10.2, which has allowed me to debug the code. 

Could you please tell us the parameter setting, such as "widget/image_size" for your results? Currently, I guess I should set it as 4096.

**Comment by githwd2016** [comment]
I have push the "requirement.txt" and the image_size is in the config/mate_v1.json

**Comment by he159ok** [comment]
Thanks a lot for your reply.
